version: "3.8"

services:
  app:
    image: python:3.10
    container_name: apsiyon_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python /app/main.py
